name: Bug
description: Something is broken
type: bug
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: One clear sentence describing what is broken.
      placeholder: The widget does not open on mobile Safari.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected
      description: What should happen?
      placeholder: The widget opens and shows the welcome message.
  - type: textarea
    id: actual
    attributes:
      label: Actual
      description: What happens instead?
      placeholder: Tapping the launcher does nothing.
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Add clear, minimal steps someone else can follow.
      placeholder: |-
        1. Open https://example.com on iOS 17 Safari
        2. Tap the chat launcher
        3. Observe nothing happens
  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Related links, issues, or extra context.
      placeholder: related:
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Logs
      description: Paste screenshots or logs that help explain the issue.
